const pastExecStrings = {
  title: "Past Executives",
  description:
    "Thank you to the previous committee executives & alumnae for building the community we have today!",
  accordionTitle: "Past Executives",
  // ADD PAST EXECUTIVES HERE
  // Add term and all of the executives of the term in the following format:
  // term: {
  //    exec1: "name",
  //    exec2: "name",
  //    ......
  // }
  // exec1 must be the chair of the corresponding term
  // exec1a and exec2a must be the co-chairs of the corresponding term
  pastExecs: {
    "Fall 2023": {
      exec1a: "Claudia M.",
      exec2a: "Maryam A.",
      exec3: "Molly X.",
      exec4: "Layne L.",
      exec5: "Amanda B.",
      exec6: "Karneet K.",
      exec7: "Shriya K.",
      exec8: "Aarushi J.",
      exec9: "Dora S.",
      exec10: "Caroline H.",
      exec11: "Madeline P.",
      exec12: "Bodhana B.",
    },
    "Spring 2023": {
      exec1a: "Leen K.",
      exec2a: "Melanie F.",
      exec3: "Veronika S.",
      exec4: "Iris C.",
      exec5: "Shriya K.",
      exec6: "Priyadarshini S.",
      exec7: "Valerie F.",
      exec8: "Madison M.",
      exec9: "Jemima V.",
      exec10: "Padena R.",
      exec11: "Madeline P.",
    },
    "Winter 2023": {
      exec1a: "Amanda B.",
      exec2a: "Kitty L.",
      exec3: "Audrey H.",
      exec4: "Layne L.",
      exec5: "Veronika S.",
      exec6: "Karneet K.",
      exec7: "Shriya K.",
      exec8: "Prasanna T.",
      exec9: "Yani M.",
      exec10: "Helena X.",
    },
    "Fall 2022": {
      exec1a: "Priyadarshini S.",
      exec2a: "Molly X.",
      exec3: "Star X.",
      exec4: "Melanie F.",
      exec5: "Claudia M.",
      exec6: "Leen K.",
      exec7: "Madison M.",
      exec8: "Richa D.",
      exec9: "Yani M.",
      exec10: "Vanessa W.",
    },
    "Spring 2022": {
      exec1a: "Kitty L.",
      exec2a: "Amanda B.",
      exec3: "Jaskomal N.",
      exec4: "Layne L.",
      exec5: "Leen K.",
      exec6: "Melanie F.",
      exec7: "Nina T.",
      exec8: "Sachi S.",
      exec9: "Star X.",
      exec10: "Jui S.",
    },
    "Winter 2022": {
      exec1: "Priyadarshini S.",
      exec2: "Amanda B.",
      exec3: "Angelina J.",
      exec4: "Claudia M.",
      exec5: "Kitty L.",
      exec6: "Leen K.",
      exec7: "Maryam A.",
      exec8: "Melanie F.",
    },
    "Fall 2021": {
      exec1a: "Sophia L.",
      exec2a: "Sakina M.",
      exec3: "Angel L.",
      exec4: "Molly X.",
      exec5: "Khloe R.",
      exec6: "Priyadarshini S.",
      exec7: "Claudia M.",
      exec8: "Angela Z.",
    },
    "Spring 2021": {
      exec1: "Audrey H.",
      exec2: "Maryam A.",
      exec3: "Celine L.",
      exec4: "Jaskomal N.",
      exec5: "Richa D.",
      exec6: "Nina T.",
      exec7: "Angelina J.",
    },
    "Winter 2021": {
      exec1: "Jacqueline L.",
      exec2: "Angel L.",
      exec3: "Iris C.",
      exec4: "Maryam A.",
      exec5: "Molly X.",
      exec6: "Nina T.",
      exec7: "Vivian L.",
    },
    "Fall 2020": {
      exec1: "Celine L.",
      exec2: "Angel L.",
      exec3: "Audrey H.",
      exec4: "Falah S.",
      exec5: "Kriti R.",
      exec6: "Molly X.",
      exec7: "Sakina M.",
      exec8: "Sophia L.",
    },
    "Spring 2020": {
      exec1: "Iris C.",
      exec2: "Angela Z.",
      exec3: "Areena A.",
      exec4: "Audrey H.",
      exec5: "Jasmine B.",
      exec6: "Linda Y.",
      exec7: "Vivian L.",
    },
    "Winter 2020": {
      exec1: "Caroline C.",
      exec2: "Areena A.",
      exec3: "Jasmine B.",
      exec4: "Jenny Y.",
      exec5: "Karolina X.",
      exec6: "Sakina M.",
      exec7: "Sophia L.",
    },
    "Fall 2019": {
      exec1: "Angelina J.",
      exec2: "Aurora D.",
      exec3: "Celine L.",
      exec4: "Helen Y.",
      exec5: "Iris C.",
      exec6: "Jacqueline L.",
      exec7: "Jenny Y.",
      exec8: "Raina D.",
    },
    "Spring 2019": {
      exec1: "Falah S.",
      exec2: "Angelina J.",
      exec3: "Kriti R.",
      exec4: "Liza C.",
      exec5: "Sakina M.",
      exec6: "Sophia L.",
    },
    "Winter 2019": {
      exec1: "Bonnie X.",
      exec2: "Caroline C.",
      exec3: "Celine L.",
      exec4: "Helen Z.",
      exec5: "Iris C.",
      exec6: "Jacqueline L.",
      exec7: "Katherine G.",
    },
    "Fall 2018": {
      exec1: "Qinrui (Ray) L.",
      exec2: "Angelina J.",
      exec3: "Bonnie X.",
      exec4: "Kriti R.",
      exec5: "Sakina M.",
      exec6: "Sophia L.",
    },
  },
};

export default pastExecStrings;
